### ISSUE TITLE
Disable logging

### ISSUE THREAD

**Issue by trmdi** [slonopot/LRCLIBee#1]
Hi, is there any way to disable logging?

**Comment by slonopot** [comment]
No, the logging is only local and does not contain any private information

**Comment by trmdi** [comment]
I meant to reduce writing to SSDs.

**Comment by slonopot** [comment]
Yeah, alright, I'll get into how modern computers work. Let's assume you're not cheap and have and got a somewhat decent SSD, 300 TBW? If you write 100 Gb a day, this will be 3000 days until exhaustion, 8.21 years. I've just checked the log files of mine, less than a megabyte total. Do the rest of the math yourself.

If you want to reduce writing, drop Windows. If you want to feel safe, configure (and regularly test) backups. If you want to get the best of SSD, drop the consumer-grade trash and buy yourself some used U.2 enterprise one and a pcie adapter for the same price or less, you'll get far better IOPS and a lifetime of writing (13+ PBW for Intel P4510?). I wouldn't write off the backups though, it's still a storage drive and they fail whether you like it or not.

I'd also like you to understand that the drives are consumables just like toothpaste, for example. If you are not babysitting your toothpaste, I won't be expecting you to do the same to your drive. If you [still] do after that explanation, then it's an issue that for another kind of expert.

**Comment by trmdi** [comment]
Ok man. I just opened the issue to see if you can add a new option to the config file e.g. `logging: off`. Don't take it so seriously.
